spring:
  application:
    name: exchange-consume

server:
  port: 8100
  
#exchange-service:
#  ribbon:
#    listOfServers: localhost:8000,localhost:8001

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    preferIpAddress: true
    metadataMap:
      instanceId: exchange-consume:8100
# must add to enable hytrix for feign
feign:
  hystrix:
    enabled: true